version: '3.8'

services:
  voicescribe:
    build: .
    container_name: voicescribe
    ports:
      - "5000:5000"
    environment:
      - API_KEY=${API_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-26214400}
    volumes:
      - /tmp:/tmp
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Commented out MinIO for Coolify deployment - use external S3 or deploy separately
# minio:
#   image: minio/minio:latest
#   container_name: voicescribe-minio
#   ports:
#     - "9000:9000"
#     - "9001:9001"
#   environment:
#     - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
#     - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin123}
#   volumes:
#     - minio_data:/data
#   command: server /data --console-address ":9001"
#   restart: unless-stopped
#   healthcheck:
#     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
#     interval: 30s
#     timeout: 20s
#     retries: 3

# volumes:
#   minio_data:
#     driver: local